### ISSUE TITLE
Multiple type support

### ISSUE THREAD

**Issue by RoshanNepal3** [mongrov/timon#15]
Scenario 1:

The ring device provides string values for Android and int/float values for iOS. To use a unified schema file across both platforms, we need support for multiple data types for values.

Example for Android:
{"date": "2024.11.08 12:00:00", "heartRate": "120"}

Example for iOS:
{"date": "2024.11.08 12:00:00", "heartRate": 120}

Scenario 2:
The temperature data from the ring device may contain both integer and float values.

Example data:
[
  {"date": "2024.10.30 05:29:59", "temperature": 34.6},
  {"date": "2024.10.30 04:59:59", "temperature": 36}
]

If the schema expects a float for temperature, the following error occurs when trying to store this data:
{"json_value": null, "message": "Field 'temperature' expected type 'float' but got 'int'", "status": 400}

If the schema expects an integer for temperature, the following error occurs:
{"json_value": null, "message": "Field 'temperature' expected type 'int' but got 'float'", "status": 400}

**Comment by AhmedBoutaraa57** [comment]
Handling multiple data types can be challenging. I've addressed this issue by promoting "int" types to "float" when the type is defined as "type": "int|float", treating it as "float|int". However, combinations like "bool|string", "int|string", or similar mixed types may still produce unexpected results during queries.

fixed in [commit](https://github.com/mongrov/timon/commit/7cf79a7ea4fc2ff4a861f2dde2333a3dde73c119)
